import React, { useEffect, useState } from 'react';
import DealerLayout from '../components/DealerLayout';
import axios from 'axios';
import { API_BASE_URL } from '../config/api';

const DealerInvoices = () => {
  const [invoices, setInvoices] = useState([]);

  useEffect(() => {
    fetchInvoices();
  }, []);

  const fetchInvoices = async () => {
    try {
      const res = await axios.get(`${API_BASE_URL}/api/invoices/dealer`);
      setInvoices(res.data);
    } catch (error) {
      // handled silently
    }
  };

  return (
    <DealerLayout>
      <div className="max-w-6xl mx-auto space-y-6">
        <h1 className="text-3xl font-bold text-gray-800 mb-2">Invoices</h1>
        <p className="text-gray-600 mb-6">
          View invoices generated by admin for your orders.
        </p>

        <div className="card">
          <h2 className="text-xl font-semibold text-gray-800 mb-4">
            Invoice List
          </h2>
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead>
                <tr className="border-b">
                  <th className="text-left py-2 text-sm font-semibold text-gray-700">
                    Invoice
                  </th>
                  <th className="text-left py-2 text-sm font-semibold text-gray-700">
                    Order
                  </th>
                  <th className="text-left py-2 text-sm font-semibold text-gray-700">
                    Amount
                  </th>
                  <th className="text-left py-2 text-sm font-semibold text-gray-700">
                    Status
                  </th>
                  <th className="text-left py-2 text-sm font-semibold text-gray-700">
                    Date
                  </th>
                </tr>
              </thead>
              <tbody>
                {invoices.length > 0 ? (
                  invoices.map((inv) => (
                    <tr key={inv._id} className="border-b">
                      <td className="py-2 text-sm text-gray-800">
                        {inv.invoiceNumber}
                      </td>
                      <td className="py-2 text-sm text-gray-800">
                        {inv.order ? inv.order._id : '-'}
                      </td>
                      <td className="py-2 text-sm text-gray-800">
                        ₹{inv.amount?.toLocaleString()}
                      </td>
                      <td className="py-2 text-sm text-gray-800 capitalize">
                        {inv.paymentStatus}
                      </td>
                      <td className="py-2 text-sm text-gray-800">
                        {new Date(inv.createdAt).toLocaleDateString()}
                      </td>
                    </tr>
                  ))
                ) : (
                  <tr>
                    <td
                      colSpan="5"
                      className="py-4 text-center text-gray-500 text-sm"
                    >
                      No invoices available
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </DealerLayout>
  );
};

export default DealerInvoices;

